vich_uploader:
    db_driver: orm
    mappings:
        replay:
            uri_prefix: /replays
            upload_destination: '%kernel.project_dir%/public/replays'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer # TODO name by game id and round or use subdirs
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
    metadata:
        type: attribute

