vich_uploader:
    db_driver: orm
    mappings:
        replay:
            uri_prefix: /replays
            upload_destination: '%kernel.project_dir%/public/replays'
            namer:
                service: Vich\UploaderBundle\Naming\UniqidNamer
            directory_namer:
                service: vich_uploader.namer_directory_property
                options: { property: 'game.id' }
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
    metadata:
        type: attribute

